---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: server
    driver:
      network:
        - ["private_network", {ip: "192.168.33.10"}]
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    run_list:
      - recipe[splunk::server]
    attributes:
  - name: forwarder
    driver:
      network:
        - ["private_network", {ip: "192.168.33.20"}]
    run_list:
      - recipe[splunk::forwarder]
    attributes:
      splunk:
        install_type: 'forwarder'
